/**
 * Fix script: Writes original lesson content directly (no Bedrock).
 * Uses hand-crafted content templates. Run once to populate all failed items.
 * Usage: npx ts-node seed/fix-with-templates.ts
 */
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'
import { DynamoDBDocumentClient, UpdateCommand } from '@aws-sdk/lib-dynamodb'

const CONTENT_TABLE = process.env.CONTENT_TABLE ?? 'ai-leader-content'
const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: 'ap-south-1' }))

const CONTENT: Record<string, string> = {
"mod-01": `As a delivery leader, you hear "AI" in every meeting, vendor pitch, and executive memo. But what does it actually mean beyond the buzzwords?\n\nArtificial Intelligence refers to computer systems that can perform tasks typically requiring human intelligence — recognizing patterns, making decisions, generating text, or predicting outcomes. The key distinction: AI systems learn from data rather than following explicitly programmed rules.\n\nFor your role, AI matters because it is reshaping how software gets built, tested, and delivered. Teams using AI-assisted tools report 20-40% productivity gains in certain tasks. But AI is not magic — it excels at pattern matching and generation, while struggling with novel reasoning, factual accuracy, and understanding context the way humans do.\n\nThree categories matter most for delivery leaders: (1) Predictive AI — forecasting timelines, risks, and resource needs; (2) Generative AI — producing code, documentation, and summaries; (3) Analytical AI — extracting insights from delivery data.\n\nPractical takeaway: This week, list three places in your current delivery process where pattern recognition or content generation could save time. Do not evaluate tools yet — just identify the opportunity spaces.`,

"mod-02": `Large Language Models are the technology behind ChatGPT, Claude, and the AI coding assistants your teams are likely already experimenting with. Understanding how they work — even at a high level — helps you set realistic expectations and make better decisions about where to deploy them.\n\nThis resource explains the core mechanics without requiring math or computer science background. As a delivery leader, you will learn why these models are remarkably capable at some tasks (summarizing, drafting, explaining code) yet unreliable at others (precise calculations, factual recall, following complex multi-step logic).\n\nThe key insight for your role: LLMs are probabilistic text generators, not knowledge databases. They predict the most likely next word based on patterns in their training data. This explains both their fluency and their tendency to confidently state incorrect things.\n\nPractical takeaway: When evaluating AI tools for your team, ask vendors this question: "What is the error rate for this specific use case, and how do users verify outputs?" This separates genuine capability from demo-ware.`,

"mod-03": `When your engineering team discusses AI integration, three terms come up repeatedly: tokens, context windows, and prompts. Understanding these concepts helps you participate meaningfully in technical discussions and make informed decisions about AI tool selection.\n\nTokens are the units AI models process — roughly 3/4 of a word in English. A 100-word paragraph is about 130 tokens. This matters because AI services charge per token, and every model has a maximum token limit for input plus output combined.\n\nThe context window is the model's "working memory" — how much text it can consider at once. Current models range from 8K to 200K tokens. A larger context window means the model can reference more information simultaneously, but costs more per request.\n\nPrompts are the instructions you give the model. The quality of output depends heavily on prompt clarity. Vague prompts produce generic responses; specific, structured prompts with examples produce dramatically better results.\n\nFor delivery leaders, the practical implication is cost planning. If your team processes 1,000 documents daily through an AI pipeline, you need to estimate: average document size in tokens, model cost per token, and expected output length.\n\nPractical takeaway: Ask your tech lead to estimate the token cost for one proposed AI feature at expected volume. Multiply by 30 days. This gives you a realistic monthly AI infrastructure cost to include in budgets.`,

"mod-04": `As AI permeates delivery conversations, a shared vocabulary becomes essential. Here are the terms you will encounter most frequently as a delivery leader:\n\nModel: The trained AI system itself. Think of it as the "brain" that processes inputs and generates outputs.\n\nInference: When a model processes a request and produces output. Each API call to an AI service is one inference.\n\nFine-tuning: Customizing a pre-trained model with your organization's specific data. Expensive but can dramatically improve accuracy for niche use cases.\n\nRAG (Retrieval-Augmented Generation): Connecting an AI model to your own data sources so it can reference current, accurate information rather than relying solely on training data.\n\nHallucination: When an AI generates plausible-sounding but factually incorrect information. A critical risk to manage in any production deployment.\n\nLatency: Time between sending a request and receiving a response. AI responses typically take 1-30 seconds depending on complexity.\n\nGrounding: Techniques to connect AI outputs to verifiable source data, reducing hallucination risk.\n\nGuardrails: Rules and filters applied to AI inputs/outputs to prevent harmful, off-topic, or inaccurate responses.\n\nPractical takeaway: In your next meeting where AI comes up, listen for these terms. If someone uses jargon you do not recognize, ask them to explain it — chances are others in the room are also unclear.`,

"mod-05": `Understanding AI's genuine capabilities — and its hard limitations — is the most important mental model for a delivery leader evaluating AI opportunities.\n\nAI excels at: Pattern recognition in large datasets, generating first drafts of text and code, summarizing long documents, translating between languages, classifying items into categories, and suggesting completions based on context.\n\nAI struggles with: Novel reasoning that requires understanding not present in training data, precise factual recall (it generates plausible text, not verified facts), multi-step logical deduction, understanding cause and effect, maintaining consistency across very long outputs, and anything requiring real-world sensory experience.\n\nFor delivery leaders, this means: AI is excellent as an accelerator for human work — drafting, reviewing, suggesting, summarizing — but unreliable as an autonomous decision-maker for anything consequential.\n\nThe "80/20 rule" applies: AI can often get you 80% of the way on a task in 20% of the time, but the remaining 20% (verification, nuance, edge cases) still requires human judgment.\n\nPractical takeaway: Pick one repetitive task your team does weekly (writing status reports, triaging bugs, drafting emails). Try using an AI tool for the first draft this week. Notice where it saves time and where human review catches errors. This direct experience builds better intuition than any article.`,

"mod-06": `AI hallucinations are one of the most important risks for delivery leaders to understand. A hallucination occurs when an AI model generates output that sounds confident and plausible but is factually wrong.\n\nWhy does this happen? Language models predict the most likely next word based on patterns. They do not have a "truth database" to check against. If a confident-sounding wrong answer has similar word patterns to correct answers, the model may generate it without any indication of uncertainty.\n\nExamples relevant to delivery: An AI summarizing a meeting might "recall" a decision that was never made. A coding assistant might reference a library function that does not exist. A document generator might cite a policy that sounds right but was never written.\n\nThe risk for your teams: If people trust AI output without verification, errors propagate. A hallucinated requirement becomes a built feature nobody asked for. A hallucinated API reference becomes a bug that takes days to diagnose.\n\nMitigation strategies: Always have humans verify AI-generated content before it enters any workflow. Use RAG (connecting AI to your actual data) to reduce hallucination. Implement "confidence scoring" where possible. Create clear team norms about what AI output requires review.\n\nPractical takeaway: Establish a team rule this week: any AI-generated content that will be shared externally or used in decision-making must be verified by a human before use. This one norm prevents most hallucination-related issues.`,

"mod-07": `As a delivery leader, understanding how generative AI differs from traditional software helps you plan differently for AI-enabled features.\n\nTraditional software is deterministic: the same input always produces the same output. You can write test cases with expected results. Bugs are reproducible. Performance is predictable.\n\nGenerative AI is probabilistic: the same input may produce different outputs each time. Testing requires statistical approaches rather than exact matching. "Bugs" may be intermittent. Performance (quality of output) varies.\n\nThis has profound implications for delivery:\n\nTesting: You cannot write traditional pass/fail test cases. Instead, you need evaluation frameworks that assess output quality across many runs.\n\nTimelines: AI features are harder to estimate because "done" is fuzzy. A feature might work 90% of the time — is that shippable?\n\nIncident response: When an AI feature produces bad output, it may not be a "bug" in the traditional sense. It might be a prompt issue, a data issue, or inherent model limitation.\n\nUser expectations: Users expect software to be consistent. AI-powered features need different UX patterns that communicate uncertainty.\n\nPractical takeaway: For any AI feature on your roadmap, ask your team: "How will we know if this is working well enough to ship?" If the answer is vague, you need to define measurable quality criteria before starting development.`,

"mod-08": `AI agents represent the next evolution beyond simple AI assistants, and as a delivery leader, you will increasingly encounter them in tool evaluations and feature proposals.\n\nA basic AI interaction is one-shot: you ask a question, get an answer. An AI agent goes further — it can plan multi-step tasks, use tools (search the web, call APIs, write files), observe results, and iterate until a goal is achieved.\n\nThink of it this way: ChatGPT answering a question is like asking a colleague for advice. An AI agent is like delegating a task to a junior team member who can independently research, draft, check their work, and deliver a result.\n\nFor delivery leaders, agents matter because:\n\n1. They can automate complex workflows (not just single steps)\n2. They introduce new failure modes — an agent might take wrong actions autonomously\n3. They require different governance than simple AI tools\n4. They blur the line between "tool" and "team member" in planning\n\nCurrent limitations: Agents still struggle with ambiguous goals, long-horizon planning, and knowing when to ask for human help versus proceeding independently. They work best on well-defined tasks with clear success criteria.\n\nPractical takeaway: When a vendor or team member proposes an "AI agent" solution, ask: "What happens when the agent gets stuck or makes a mistake? What is the human escalation path?" Good agent design always includes guardrails and human-in-the-loop checkpoints.`,

"mod-09": `As a delivery leader, understanding the timeline of AI development helps you contextualize the current moment and make better predictions about what comes next.\n\nThis resource traces AI from its theoretical origins through today's generative AI wave. The key insight for delivery leaders: AI is not a sudden invention — it is the result of decades of compounding research that recently hit an inflection point when massive compute, large datasets, and transformer architecture converged.\n\nFor your role, this history explains why AI tools went from "interesting demo" to "production-ready" seemingly overnight between 2022 and 2024. It also helps you answer the question executives and team members ask: "Is this just hype, or is it real?"\n\nThe structural differences between this wave and previous "AI winters" are concrete: the cost of compute continues dropping, data availability keeps growing, and the transformer architecture scales predictably. These are not hype-dependent factors.\n\nPractical takeaway: Next time someone dismisses AI as "just another hype cycle," you can point to the specific structural factors that make this wave different. Conversely, if someone claims AI will replace all knowledge work next year, the history shows that even rapid progress takes time to mature into reliable production systems.`
}

async function fixAll() {
  const ids = Object.keys(CONTENT)
  console.log(`Fixing ${ids.length} items with hand-written content...`)

  for (const id of ids) {
    await ddb.send(new UpdateCommand({
      TableName: CONTENT_TABLE,
      Key: { contentId: id },
      UpdateExpression: 'SET aiSummary = :s',
      ExpressionAttributeValues: { ':s': CONTENT[id] }
    }))
    console.log(`  ✓ ${id}`)
  }

  console.log(`\n✅ Fixed ${ids.length} items. Run the remaining modules in a Part 2 script.`)
}

fixAll().catch(console.error)
